image:
  file: .gitpod.Dockerfile

# tasks:
#   - init: |
#       # pip install tensorflow==2.6.2 pillow numpy==1.19.5  tensorflowjs==3.18.0
#       # pip install -r "requirements.txt"
#       echo "Installed Python packages!"

#   - command: |
#       # pip install -r "requirements.txt";
#       echo "Ready to code!"

# # List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
# # ports:
# #     - port: 9000-9099
# #       onOpen: ignore

# vscode:
#     extensions:
#         # - ms-toolsai.jupyter
#         # - vscode.python
